
<?php
/**
 * @package     Wright
 * @subpackage  Template File
 *
 * @copyright   Copyright (C) 2005 - 2013 Joomlashack. Meritage Assets.  All rights reserved.
 * @license     GNU General Public License version 2 or later; see LICENSE.txt
 *
 * Do not edit this file directly. You can copy it and create a new file called
 * 'custom.php' in the same folder, and it will override this file. That way
 * if you update the template ever, your changes will not be lost.
 */
// no direct access
defined('_JEXEC') or die('Restricted access');
?>
<doctype>
	<html>
		<head>
			<w:head /> 
			<link href='https://fonts.googleapis.com/css?family=Varela+Round' rel='stylesheet' type='text/css'>
			<link href='https://fonts.googleapis.com/css?family=Quattrocento+Sans:400,700' rel='stylesheet' type='text/css'>
		</head>
		<body class="<?php   echo $responsive ?>">
			<!-- toolbar -->
			<?php if ($techieLateralMenu) : ?>
			<div class="techie-container">
			<?php endif ?>
			<?php if ($this->countModules('toolbar')) : ?>
			<w:nav containerClass="<?php echo $containerClass ?>" rowClass="<?php echo $gridMode; ?>" wrapClass="navbar-fixed-top navbar-inverse" type="toolbar" name="toolbar" />
			<?php endif; ?>
			<!-- toolbar end -->
			<!-- header -->
			<header id="header" class="<?php echo (!$techieSlideshow ? '' : 'techieSlideshow');  ?>">
				<div class="top-object"></div>
				<!-- Place holder inner images -->
				<?php if ($bg && !$techieSlideshow) : ?>
	          		<div class="bg-wrapp">
		                <div class="bg-wrapp-inner">
		                	<img id="bg-header" src="<?php echo JURI::root(true) . $bg; ?>" />
		                </div>
	            	</div>
       			 <?php endif ?>				
				<!-- Place holder inner images end -->
				<!-- logo -->
				<div class="<?php echo $containerClass ?>">
					<div class="header-inner"> 
						<w:logo name="top"/>
						<?php if ($techieLateralMenu) : ?>
						<div class="toolbar-collapse-btn">
						<div class="legend-menu">MENU</div>
						<div class="menu-icons-container">
						<span class="icon-bar"></span>
						<span class="icon-bar"></span>
						<span class="icon-bar"></span>
						</div>
						</div>
						 <?php endif ?>			
						<div class="clear"></div> 
					</div>
					<?php if (!$techieSlideshow) : ?>
					<div id="current-menu-item"><h1><?php echo $menu_itemActive; ?></h1></div>	
					<?php else: ?>
					 	<div class="<?php echo $containerClass ?> slide-arrows-container">
					 	<a id="prevslide" class="load-item"></a>
			            <a id="nextslide" class="load-item"></a>	
					 	<div id="current-slide-item" class="item"><h1>Designed to make your life easier.</h1>
					 	<p>
					 	Since 2005, Joomlashack has been building cool templates.
					 	We call them “Strictly Joomla” because in most cases you can 
					 	install them using only the Joomla CMS’s built-in features, making it simple, quick, and easy.
					 	</p>	
					 	</div>
					 	</div>	
					<?php endif ?>
						  
					<!-- logo end -->
				</div>
			</header> 
			<!-- header end -->
			<?php if ($techieSlideshow) : ?>
			<div class="<?php echo (!$techieSlideshow ? '' : 'techieSlideshowContainer');  ?>">
			<?php endif ?>
			<!-- top -->
			<?php if ($this->countModules('top')) : ?> 
			<div id="top-header"> 
				<div class="<?php echo $containerClass ?>">
					<w:module type="<?php echo $gridMode; ?>" name="top" chrome="wrightflexgrid" extradivs="module" />
				</div>
			</div>
			<?php endif; ?>
			<!-- top end -->
			<!-- breadcrumbs -->
			<?php if ($this->countModules('breadcrumbs')) : ?>
			<div id="breadcrumbs">
				<div class="<?php echo $containerClass ?>">
					<div class="<?php echo $gridMode; ?>">
						<div class="span12">
							<w:module type="single" name="breadcrumbs" chrome="none" />
						</div>
					</div>
				</div>
			</div>
			<?php endif; ?>
			<!-- breadcrumbs end -->
			<!-- Main container -->
				<!-- Featured -->
				<?php if ($this->countModules('featured')) : ?>
				<div class="<?php echo $containerClass ?>">	
                <div id="featured">
                	<w:module type="none" name="featured" chrome="xhtml" />
				</div>
				</div>
                <?php endif; ?>	
                <!-- Featured end -->
				<!-- grid-top -->
				<?php if ($this->countModules('grid-top')) : ?>	
				<div id="grid-top">
				<div class="<?php echo $containerClass ?>">		
					<w:module type="row-fluid" name="grid-top" chrome="wrightflexgrid" extradivs="module" />
				</div>
				</div>
				<?php endif; ?>
				<!-- grid-top end -->
				<!-- grid-top2 -->
				<?php if ($this->countModules('grid-top2')) : ?>
				<!-- grid-top2 -->
				<div id="grid-top2">
					<div class="<?php echo $containerClass ?>">	
					<w:module type="<?php echo $gridMode; ?>" name="grid-top2" chrome="wrightflexgrid" extradivs="module" />
				</div>
				</div>
				<?php endif; ?>
				<!-- grid-top2 end -->
				<?php if ($this->countModules('content') || $this->countModules('content2')) : ?>
				<div id="content-wrapper">
				<?php endif; ?>	
				<!-- content -->
				<?php if ($this->countModules('content')) : ?>
				<div id="content">
					<div class="<?php echo $containerClass ?>">	
					<w:module type="<?php echo $gridMode; ?>" name="content" chrome="wrightflexgrid" extradivs="module" />
					</div>
				</div>
				<?php endif; ?>
				<!-- content end -->
				<!-- content2 -->
				<?php if ($this->countModules('content2')) : ?>
				<div id="content2">
				<div class="<?php echo $containerClass ?>">	
					<w:module type="<?php echo $gridMode; ?>" name="content2" chrome="wrightflexgrid" extradivs="module" />
				</div>
				</div>
				<?php endif; ?>
				<!-- content2 end -->
				<?php if ($this->countModules('content') || $this->countModules('content2')) : ?>
				</div>
				<?php endif; ?>	
				<div class="<?php echo $containerClass ?>">
				<div id="main-content" class="<?php echo $gridMode; ?>">
					<!-- sidebar1 -->
					<aside id="sidebar1">
						<w:module name="sidebar1" chrome="xhtml" />
					</aside>
					<!-- sidebar1 end -->
					<!-- main -->
					<section id="main">
						<?php if ($this->countModules('above-content')) : ?>
						<!-- above-content -->
						<div id="above-content">
						<w:module type="none" name="above-content" chrome="xhtml" />
						</div>
						<?php endif; ?>
						<!-- above-content end -->
						<!-- component -->
						<w:content /> 
						<!-- component end -->
						<!-- below-content --> 
						<?php if ($this->countModules('below-content')) : ?>
						<div id="below-content">
							<w:module type="none" name="below-content" chrome="xhtml" />
						</div>
						<?php endif; ?> 
						<!-- below-content end -->
					</section>
					<!-- main end -->
					<!-- sidebar2 -->
					<aside id="sidebar2">
						<w:module name="sidebar2" chrome="xhtml" />
					</aside>
					<!-- sidebar2 end -->
				</div>
				</div>
			<!-- main container end -->
				<!-- grid-bottom -->
				<?php if ($this->countModules('grid-bottom')) :	?> 
				<div id="grid-bottom" >
					<div class="<?php echo $containerClass ?>">
					<w:module type="<?php echo $gridMode; ?>" name="grid-bottom" chrome="wrightflexgrid" extradivs="module" />
					</div>
				</div> 
				<?php endif; ?>
				<!-- grid-bottom end --> 
				<!-- grid-bottom2 --> 
				<?php if ($this->countModules('grid-bottom2')) : ?>
				<div id="grid-bottom2" >		
				<div class="<?php echo $containerClass ?>">
					<w:module type="<?php echo $gridMode; ?>" name="grid-bottom2" chrome="wrightflexgrid" extradivs="module" />
				</div>
				</div>  
				<?php endif; ?>
				<!-- grid-bottom2 end -->
			<!-- footer -->
			<div class="wrapper-footer">
				<footer id="footer" <?php if ($this->params->get('stickyFooter',1)) : ?> class="sticky" <?php endif; ?> >
					<!-- bottom-menu -->
					<?php if ($this->countModules('bottom-menu')) : ?>
					<w:nav containerClass="<?php echo $containerClass ?>" rowClass="<?php echo $gridMode; ?>" name="bottom-menu" wrapClass="navbar-transparent" />
					<?php endif; ?>
					<!-- bottom-menu end -->
					<div class="<?php echo $containerClass ?> footer-content">
						<?php if ($this->countModules('footer')) : ?>
						<w:module type="<?php echo $gridMode; ?>" name="footer" chrome="wrightflexgrid" />
						<?php endif; ?>
						<w:footer /> 
					</div>
				</footer>
			</div>
			<?php if ($techieSlideshow) : ?>
				</div>
			<?php endif ?>
			<?php if ($techieLateralMenu) : ?>
			</div>
			<?php endif ?>
			<!-- footer end -->
			<!-- lateral-menu -->
			<?php if ($this->countModules('lateral-menu') && $techieLateralMenu) : ?>
			<div id="lateral-menu">
			<w:module type="single" name="lateral-menu" chrome="xhtml" extradivs="module" />
			</div>
			<?php endif; ?>
			<!-- lateral-menu end -->
		<?php if ($techieSlideshow) : ?>
        <script type="text/javascript" src="<?php echo JURI::root(true) ?>/templates/js_techie/js/jquery.easing.min.js"></script>
        <script type="text/javascript" src="<?php echo JURI::root(true) ?>/templates/js_techie/js/supersized.min.js"></script>
        <script type="text/javascript" src="<?php echo JURI::root(true) ?>/templates/js_techie/js/supersized.shutter.min.js"></script>

        <script type="text/javascript">
            jQuery(function(){
                jQuery.supersized({
                    // Functionality
                    slideshow               :   1,          // Slideshow on/off
                    autoplay                :   1,          // Slideshow starts playing automatically
                    start_slide             :   1,          // Start slide (0 is random)
                    stop_loop               :   0,          // Pauses slideshow on last slide
                    random                  :   0,          // Randomize slide order (Ignores start slide)
                    slide_interval          :   12000,      // Length between transitions
                    transition              :   3,          // 0-None, 1-Fade, 2-Slide Top, 3-Slide Right, 4-Slide Bottom, 5-Slide Left, 6-Carousel Right, 7-Carousel Left
                    transition_speed        :   300,        // Speed of transition
                    new_window              :   1,          // Image links open in new window/tab
                    pause_hover             :   1,          // Pause slideshow on hover
                    keyboard_nav            :   1,          // Keyboard navigation on/off
                    performance             :   1,          // 0-Normal, 1-Hybrid speed/quality, 2-Optimizes image quality, 3-Optimizes transition speed // (Only works for Firefox/IE, not Webkit)
                    image_protect           :   1,          // Disables image dragging and right click with Javascript

                    // Size & Position
                    min_width               :   0,          // Min width allowed (in pixels)
                    min_height              :   0,          // Min height allowed (in pixels)
                    vertical_center         :   0,          // Vertically center background
                    horizontal_center       :   1,          // Horizontally center background
                    fit_always              :   0,          // Image will never exceed browser width or height (Ignores min. dimensions)
                    fit_portrait            :   0,          // Portrait images will not exceed browser height
                    fit_landscape           :   0,          // Landscape images will not exceed browser width

                    // Components
                    slide_links             :   'blank',    // Individual links for each slide (Options: false, 'num', 'name', 'blank')
                    thumb_links             :   0,          // Individual thumb links for each slide
                    thumbnail_navigation    :   0,          // Thumbnail navigation

                    slides                  :   [           // Slideshow Images
                                                        {image : '<?php echo JURI::root(true) . $slideshowImageOneRute; ?>'},
                                                        {image : '<?php echo JURI::root(true) . $slideshowImageTwoRute; ?>'},
                                                        {image : '<?php echo JURI::root(true) . $slideshowImageThreeRute ?>'},
                                                        {image : '<?php echo JURI::root(true) . $slideshowImageFourRute ?>'}
                                                ],
                    // Theme Options
                    progress_bar            :   0,          // Timer for each slide
                    mouse_scrub             :   0
                });
            });
            
             <?php if ($bsMode) : ?>
             var BsModeFluid = true;
             <?php else: ?>
             var BsModeFluid = false;
             <?php endif; ?> 
                        
            
        </script>
  	  <?php endif; ?>
			<script type='text/javascript' src='<?php echo JURI::root(true) ?>/templates/js_techie/js/techie.js'></script>
		</body>
	</html>
</doctype>